# Welcome to Plus!
#
# This config file affects your whole blog.
# This file is *NOT* reloaded automatically when you use 'bundle exec jekyll serve'.
# If you change this file, please restart the server process.

# Site settings
title:              auralgadgets
description:        hearing aids have proven being better for women at family, work, health, sports, etc. But, not all are designed the same. We’ve reviewed and found that..
url:                http://auralgadgets.com # Site base hostname & protocol, e.g. http://example.com
baseurl:            # Site subpath, e.g. /blog
logo_image:
  dark:            logo.png # Dark logo e.g logo-dark.svg upload to /uploads/ folder, used in header, mobile navigation and page sidebar About widget
  light:           logo.png # Light logo e.g. logo-light.svg upload to /uploads/ folder, used in footer About widget
permalink:          /:title/ # Permalink URLs structure, for permalink style options see: https://jekyllrb.com/docs/permalinks/
date_format:        "%B %-d, %Y" # refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
uploads:            /uploads/ # Path to post content assets directory i.e post images, pdfs etc
paginate:           7 # Number of posts displayed on blog page
paginate_path:      "/blog/:num/" # Blog path
google_analytics:   # Google analytics code, get your code here https://www.google.com/analytics/
disqus:
  shortname:        # Disqus comments shortname, requires Disqus account https://disqus.com/

instagram_accesstoken:

footer:             # Default footer image settings
  copyright:        Made by auralgadgets

# navbar settings
navbar_primary:
  sticky:           false
  social:           false
  search:           false

# Social share buttons
social_share:
  twitter:          true
  facebook:         true
  linkedin:         false
  pinterest:        false
  reddit:           true

# Social networks
social_networks:
  email:
  website:
  facebook:         https://www.facebook.com/auralgadgets-102256021952797
  flickr:
  dribbble:
  github:
  reddit:           https://www.reddit.com/user/auralgadgets
  instagram:
  linkedin:
  pinterest:        https://www.pinterest.com/sarahhollen96/_saved/
  twitter:          https://twitter.com/WatchPro
  vimeo:
  youtube:          https://www.youtube.com/channel/UC6qerLgiNh2aLCk5SQgOJdg

# Strings
strings:
  author_by:        By

# Build settings
markdown:           kramdown
highlighter:        rouge

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-avatar
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - CHANGELOG
  - LICENSE
  - README
  - /docs

sass:
  style:            compressed

# collections:
collections:
  authors:
    output: true
  category:
    output: true

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: page
      sidebar: left
  # _authors
  - scope:
      path: ""
      type: authors
    values:
      layout: author
  # _category
  - scope:
      path: ""
      type: category
    values:
      layout: category
